import { colors } from '../colors'
import { IMTag } from '../utils'

export const TAGS: IMTag[] = [
  // Types of work
  {
    value: 'article',
    label: 'Article',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'book',
    label: 'Book',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'broadcast',
    label: 'Broadcast',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'catalog',
    label: 'Catalog',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'chapter',
    label: 'Chapter',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'conference_article',
    label: 'Conference article',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'encyclopedia_article',
    label: 'Encyclopedia article',
    color: colors.work,
    group: 'Type of work',
  },
  { value: 'film', label: 'Film', color: '#4fcdf7', group: 'Type of work' },
  {
    value: 'historical_document',
    label: 'Historical document',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'journal_article',
    label: 'Journal article',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'legal_document',
    label: 'Legal document',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'magazine_article',
    label: 'Magazine article',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'manuscript',
    label: 'Manuscript',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'metastudy',
    label: 'Metastudy',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'news_article',
    label: 'News article',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'opinion_piece',
    label: 'Opinion piece',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'organization',
    label: 'Organization',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'personal_communication',
    label: 'Personal communication',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'presentation',
    label: 'Presentation',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'research_summary',
    label: 'Research summary',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'scholarly_book',
    label: 'Scholarly book',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'study_report',
    label: 'Study report',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'textbook',
    label: 'Textbook',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'thesis',
    label: 'Thesis',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'website',
    label: 'Website',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'working_paper',
    label: 'Working paper',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'public_goods_infrastructure',
    label: 'Public goods infrastructure',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'service',
    label: 'Service',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'campaign',
    label: 'Campaign',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'study',
    label: 'Study',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'workshop',
    label: 'Workshop',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'course',
    label: 'Course',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'training',
    label: 'Training',
    color: colors.work,
    group: 'Type of work',
  },
  // Fields of work
  {
    value: 'ai_governance',
    label: 'AI governance',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'biosecurity',
    label: 'Biosecurity',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'civilizational_resilience',
    label: 'Civilizational resilience',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'climate_change',
    label: 'Climate change',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'democractic_decision-making',
    label: 'Democractic decision-making',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'farmed_animal_welfare',
    label: 'Farmed animal welfare',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'global_priorities_research',
    label: 'Global priorities research',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'great_power_conflict',
    label: 'Great power conflict',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'healthcare',
    label: 'Healthcare',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'medicine',
    label: 'Medicine',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'information_security',
    label: 'Information security',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'institutional_decision-making',
    label: 'Institutional decision-making',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'international_development',
    label: 'International development',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'development_economics',
    label: 'Development economics',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'longevity',
    label: 'Longevity',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'mental_health',
    label: 'Mental health',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'metascience',
    label: 'Metascience',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'moral_enhancement',
    label: 'Moral enhancement',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'nuclear_security',
    label: 'Nuclear security',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'progress_studies',
    label: 'Progress studies',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'suffering_and_existential_risks',
    label: 'Suffering and existential risks',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'technical_ai_safety',
    label: 'Technical AI safety',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'wild_animal_welfare',
    label: 'Wild animal welfare',
    color: colors.field,
    group: 'Field of work',
  },
  {
    value: 'other_type_of_work',
    label: 'Other type of work',
    color: colors.other,
    group: 'Other',
  },
  {
    value: 'other_field_of_work',
    label: 'Other field of work',
    color: colors.other,
    group: 'Other',
  },
]
