import { colors } from '../colors'
import { IMTag } from '../utils'

export const TAGS: IMTag[] = [
  // Types of work
  {
    value: 'communication',
    label: 'Communication',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'research',
    label: 'Research',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'education',
    label: 'Education',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'organization',
    label: 'Organization',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'infrastructure',
    label: 'Infrastructure',
    color: colors.work,
    group: 'Type of work',
  },
  {
    value: 'other_type_of_work',
    label: 'Other type of work',
    color: colors.other,
    group: 'Type of work',
  },
  // Fields of work
  {
    value: 'corrigibility',
    label: 'Corrigibility',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'decision_theory',
    label: 'Decision Theory',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'embedded_agency',
    label: 'Embedded Agency',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'infra-bayesianism',
    label: 'Infra-Bayesianism',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'inner_alignment',
    label: 'Inner Alignment',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'multipolar_scenarios',
    label: 'Multipolar Scenarios',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'outer_alignment',
    label: 'Outer Alignment',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'symbol_grounding',
    label: 'Symbol Grounding',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'agent_foundations',
    label: 'Agent Foundations',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'ai-assisted_ai_automated_alignment',
    label: 'AI-assisted/AI automated Alignment',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'ai_boxing',
    label: 'AI Boxing (Containment)',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'debate',
    label: 'Debate (AI safety technique)',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'eliciting_latent_knowledge',
    label: 'Eliciting Latent Knowledge (ELK)',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'factored_cognition',
    label: 'Factored Cognition',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'inverse_reinforcement_learning',
    label: 'Inverse Reinforcement Learning',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'iterated_amplification',
    label: 'Iterated Amplification ',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'mild_optimization',
    label: 'Mild Optimization',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'oracle_ai',
    label: 'Oracle AI',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'rlhf',
    label: 'RLHF',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'shard_theory',
    label: 'Shard Theory',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'transparency_interpretability',
    label: 'Transparency/Interpretability',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'tripwire',
    label: 'Tripwire',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'value_learning',
    label: 'Value Learning',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'ai_alignment_fieldbuilding',
    label: 'AI Alignment Fieldbuilding ',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'ai_governance',
    label: 'AI Governance',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'ai_persuasion',
    label: 'AI Persuasion',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'ai_services',
    label: 'AI Services (CAIS)',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'restrain_ai_development',
    label: 'Restrain AI Development',
    color: colors.field,
    group: 'Field of AI safety',
  },
  {
    value: 'compute_governance',
    label: 'Compute ',
    color: colors.field,
    group: 'Field of AI safety',
  },
  // Cause areas
  {
    value: 'existential_and_suffering_risks',
    label: 'Existential and suffering risks',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'ai_safety',
    label: 'AI safety',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'biosecurity',
    label: 'Biosecurity',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'civilizational_resilience',
    label: 'Civilizational resilience',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'climate_change',
    label: 'Climate change',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'democractic_decision-making',
    label: 'Democractic decision-making',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'farmed_animal_welfare',
    label: 'Farmed animal welfare',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'forecasting',
    label: 'Forecasting',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'global_priorities_research',
    label: 'Global priorities research',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'great_power_conflict',
    label: 'Great power conflict',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'healthcare',
    label: 'Healthcare',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'medicine',
    label: 'Medicine',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'information_security',
    label: 'Information security',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'institutional_decision-making',
    label: 'Institutional decision-making',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'international_development',
    label: 'International development',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'development_economics',
    label: 'Development economics',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'longevity',
    label: 'Longevity',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'mental_health',
    label: 'Mental health',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'metascience',
    label: 'Metascience',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'moral_enhancement',
    label: 'Moral enhancement',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'nuclear_security',
    label: 'Nuclear security',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'progress_studies',
    label: 'Progress studies',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'wild_animal_welfare',
    label: 'Wild animal welfare',
    color: colors.causearea,
    group: 'Cause area',
  },
  {
    value: 'other_field_of_work',
    label: 'Other cause area',
    color: colors.other,
    group: 'Cause area',
  },
]
