
export type IMTag = {
  value: string;
  label: string;
  color: string;
}

export const TAGS: IMTag[] = [
  { value: 'ai_governance', label: 'AI governance', color: '#063971' },
  { value: 'biosecurity', label: 'Biosecurity', color: '#497E76' },
  { value: 'civilizational_resilience', label: 'Civilizational resilience', color: '#1C1C1C' },
  { value: 'climate_change', label: 'Climate change', color: '#C7B446' },
  { value: 'democractic_decision-making', label: 'Democractic decision-making', color: '#B8B799' },
  { value: 'farmed_animal_welfare', label: 'Farmed animal welfare', color: '#382C1E' },
  { value: 'global_priorities_research', label: 'Global priorities research', color: '#2F4538' },
  { value: 'great_power_conflict', label: 'Great power conflict', color: '#A2231D' },
  { value: 'healthcare', label: 'Healthcare', color: '#826C34' },
  { value: 'medicine', label: 'Medicine', color: '#6A5D4D' },
  { value: 'information_security', label: 'Information security', color: '#8673A1' },
  { value: 'institutional_decision-making', label: 'Institutional decision-making', color: '#4E5452' },
  { value: 'international_development', label: 'International development', color: '#AF2B1E' },
  { value: 'development_economics', label: 'Development economics', color: '#6C6874' },
  { value: 'longevity', label: 'Longevity', color: '#CB3234' },
  { value: 'mental_health', label: 'Mental health', color: '#317F43' },
  { value: 'metascience', label: 'Metascience', color: '#474B4E' },
  { value: 'moral_enhancement', label: 'Moral enhancement', color: '#6C7156' },
  { value: 'nuclear_security', label: 'Nuclear security', color: '#587246' },
  { value: 'progress', label: 'Progress', color: '#5D9B9B' },
  { value: 'suffering_and_existential_risks', label: 'Suffering and existential risks', color: '#39352A' },
  { value: 'technical_ai_safety', label: 'Technical AI safety', color: '#FFA420' },
  { value: 'wild_animal_welfare', label: 'Wild animal welfare', color: '#8B8C7A' },
  { value: 'article', label: 'Article', color: '#412227' },
  { value: 'book', label: 'Book', color: '#EAE6CA' },
  { value: 'broadcast', label: 'Broadcast', color: '#26252D' },
  { value: 'catalog', label: 'Catalog', color: '#1E5945' },
  { value: 'chapter', label: 'Chapter', color: '#293133' },
  { value: 'conference_article', label: 'Conference article', color: '#F39F18' },
  { value: 'encyclopedia_article', label: 'Encyclopedia article', color: '#89AC76' },
  { value: 'film', label: 'Film', color: '#E1CC4F' },
  { value: 'historical_document', label: 'Historical document', color: '#3B83BD' },
  { value: 'journal_article', label: 'Journal article', color: '#5D9B9B' },
  { value: 'legal_document', label: 'Legal document', color: '#1E5945' },
  { value: 'magazine_article', label: 'Magazine article', color: '#6C3B2A' },
  { value: 'manuscript', label: 'Manuscript', color: '#8A9597' },
  { value: 'metastudy', label: 'Metastudy', color: '#781F19' },
  { value: 'news_article', label: 'News article', color: '#35682D' },
  { value: 'opinion_piece', label: 'Opinion piece', color: '#F6F6F6' },
  { value: 'other', label: 'Other', color: '#464531' },
  { value: 'personal_communication', label: 'Personal communication', color: '#9C9C9C' },
  { value: 'presentation', label: 'Presentation', color: '#755C48' },
  { value: 'research_summary', label: 'Research summary', color: '#E7EBDA' },
  { value: 'scholarly_book', label: 'Scholarly book', color: '#D6AE01' },
  { value: 'study_report', label: 'Study report', color: '#3D642D' },
  { value: 'textbook', label: 'Textbook', color: '#FF7514' },
  { value: 'thesis', label: 'Thesis', color: '#FFA420' },
  { value: 'website', label: 'Website', color: '#18171C' },
  { value: 'working_paper', label: 'Working paper', color: '#3B3C36' },
];
