
export type IMTag = {
  value: string;
  label: string;
  color: string;
  group: string;
}

export const TAGS: IMTag[] = [
  { value: 'ai_governance', label: 'AI governance', color: '#063971', group: 'Field of work' },
  { value: 'biosecurity', label: 'Biosecurity', color: '#497E76', group: 'Field of work' },
  { value: 'civilizational_resilience', label: 'Civilizational resilience', color: '#1C1C1C', group: 'Field of work' },
  { value: 'climate_change', label: 'Climate change', color: '#C7B446', group: 'Field of work' },
  { value: 'democractic_decision-making', label: 'Democractic decision-making', color: '#B8B799', group: 'Field of work' },
  { value: 'farmed_animal_welfare', label: 'Farmed animal welfare', color: '#382C1E', group: 'Field of work' },
  { value: 'global_priorities_research', label: 'Global priorities research', color: '#2F4538', group: 'Field of work' },
  { value: 'great_power_conflict', label: 'Great power conflict', color: '#A2231D', group: 'Field of work' },
  { value: 'healthcare', label: 'Healthcare', color: '#826C34', group: 'Field of work' },
  { value: 'medicine', label: 'Medicine', color: '#6A5D4D', group: 'Field of work' },
  { value: 'information_security', label: 'Information security', color: '#8673A1', group: 'Field of work' },
  { value: 'institutional_decision-making', label: 'Institutional decision-making', color: '#4E5452', group: 'Field of work' },
  { value: 'international_development', label: 'International development', color: '#AF2B1E', group: 'Field of work' },
  { value: 'development_economics', label: 'Development economics', color: '#6C6874', group: 'Field of work' },
  { value: 'longevity', label: 'Longevity', color: '#CB3234', group: 'Field of work' },
  { value: 'mental_health', label: 'Mental health', color: '#317F43', group: 'Field of work' },
  { value: 'metascience', label: 'Metascience', color: '#474B4E', group: 'Field of work' },
  { value: 'moral_enhancement', label: 'Moral enhancement', color: '#6C7156', group: 'Field of work' },
  { value: 'nuclear_security', label: 'Nuclear security', color: '#587246', group: 'Field of work' },
  { value: 'progress', label: 'Progress', color: '#5D9B9B', group: 'Field of work' },
  { value: 'suffering_and_existential_risks', label: 'Suffering and existential risks', color: '#39352A', group: 'Field of work' },
  { value: 'technical_ai_safety', label: 'Technical AI safety', color: '#FFA420', group: 'Field of work' },
  { value: 'wild_animal_welfare', label: 'Wild animal welfare', color: '#8B8C7A', group: 'Field of work' },
  { value: 'article', label: 'Article', color: '#412227', group: 'Type of work' },
  { value: 'book', label: 'Book', color: '#EAE6CA', group: 'Type of work' },
  { value: 'broadcast', label: 'Broadcast', color: '#26252D', group: 'Type of work' },
  { value: 'catalog', label: 'Catalog', color: '#1E5945', group: 'Type of work' },
  { value: 'chapter', label: 'Chapter', color: '#293133', group: 'Type of work' },
  { value: 'conference_article', label: 'Conference article', color: '#F39F18', group: 'Type of work' },
  { value: 'encyclopedia_article', label: 'Encyclopedia article', color: '#89AC76', group: 'Type of work' },
  { value: 'film', label: 'Film', color: '#E1CC4F', group: 'Type of work' },
  { value: 'historical_document', label: 'Historical document', color: '#3B83BD', group: 'Type of work' },
  { value: 'journal_article', label: 'Journal article', color: '#5D9B9B', group: 'Type of work' },
  { value: 'legal_document', label: 'Legal document', color: '#1E5945', group: 'Type of work' },
  { value: 'magazine_article', label: 'Magazine article', color: '#6C3B2A', group: 'Type of work' },
  { value: 'manuscript', label: 'Manuscript', color: '#8A9597', group: 'Type of work' },
  { value: 'metastudy', label: 'Metastudy', color: '#781F19', group: 'Type of work' },
  { value: 'news_article', label: 'News article', color: '#35682D', group: 'Type of work' },
  { value: 'opinion_piece', label: 'Opinion piece', color: '#F6F6F6', group: 'Type of work' },
  { value: 'other', label: 'Other', color: '#464531', group: 'Type of work' },
  { value: 'personal_communication', label: 'Personal communication', color: '#9C9C9C', group: 'Type of work' },
  { value: 'presentation', label: 'Presentation', color: '#755C48', group: 'Type of work' },
  { value: 'research_summary', label: 'Research summary', color: '#E7EBDA', group: 'Type of work' },
  { value: 'scholarly_book', label: 'Scholarly book', color: '#D6AE01', group: 'Type of work' },
  { value: 'study_report', label: 'Study report', color: '#3D642D', group: 'Type of work' },
  { value: 'textbook', label: 'Textbook', color: '#FF7514', group: 'Type of work' },
  { value: 'thesis', label: 'Thesis', color: '#FFA420', group: 'Type of work' },
  { value: 'website', label: 'Website', color: '#18171C', group: 'Type of work' },
  { value: 'working_paper', label: 'Working paper', color: '#3B3C36', group: 'Type of work' },
];
